# Configuração para rodar na Nuvem com PostgreSQL da Render
spring.datasource.url=${INTERNAL_DATABASE_URL:jdbc:mysql://localhost:3306/auroraprojeto?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC}
spring.datasource.username=${DB_USER:root}
spring.datasource.password=${DB_PASSWORD:123}

# Configurações do Hibernate / JPA automáticas para o banco que estiver ativo
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true