# Configuração para rodar na Nuvem com PostgreSQL da Render
spring.datasource.url=${INTERNAL_DATABASE_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}

# Configurações do Hibernate / JPA automáticas
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true