# Configuração Dinâmica do Banco de Dados (Lê da nuvem ou usa o padrão local)
spring.datasource.url=${MYSQLURL:jdbc:mysql://localhost:3306/auroraprojeto?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC}
spring.datasource.username=${MYSQLUSER:root}
spring.datasource.password=${MYSQLPASSWORD:123}

# Configurações do Hibernate / JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect